#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_COLOR_DEPTH 16
#define LV_MEM_SIZE (128U * 1024U)
#define LV_USE_BUILTIN_MALLOC 1
#define LV_USE_SDL 1
#define LV_USE_QRCODE 1
#define LV_SDL_INCLUDE_PATH <SDL2/SDL.h>
#define LV_SDL_RENDER_MODE LV_DISPLAY_RENDER_MODE_PARTIAL
#define LV_SDL_BUF_COUNT 2
#define LV_SDL_ACCELERATED 0
#define LV_SDL_FULLSCREEN 0
#define LV_SDL_DIRECT_EXIT 0
#define LV_DEF_REFR_PERIOD 16
#define LV_USE_ASSERT_NULL 1
#define LV_USE_ASSERT_MALLOC 1
#define LV_ASSERT_HANDLER_INCLUDE <assert.h>
#define LV_ASSERT_HANDLER assert(0);
#define LV_COLOR_MIX_ROUND_OFS 128
#define LV_OBJ_STYLE_CACHE 1
#define LV_TXT_BREAK_CHARS " ,.;:-_)}"
#define LV_USE_THEME_MONO 0
#define LV_USE_LOG 0
#define LV_USE_OS LV_OS_NONE

#endif
